#!/bin/sh

_xcpu() { 
  echo "Caught SIGXCPU signal!" 
  #kill -TERM "$child" 2>/dev/null
  kill -TERM `pstree -p $child | perl -ne 'print "$1\n" while /\((\d+)\)/g'`
  pkill tatl
}

trap _xcpu XCPU
trap _xcpu TERM

#cat $0.jail/$$.tmp
F="<<1>>( $1 )"
echo "$F"
#--noprofile is not required on my 16.04 VM, but is on my 14.04 VPN
cd $0.jail
if command -v tatl
then exe="--private-bin=tatl tatl" 
else exe="--private-bin=true         ./tatl" 
fi
echo firejail --noprofile --private-etc=foo --private-tmp --net=none --shell=none --private-dev --private=.  $exe $$.tmp &

#(echo 1; echo "$1"; yes 2) | firejail --noprofile --private-etc=foo --private-tmp --net=none --shell=none --private-dev --private=.  $exe $$.tmp &
firejail --noprofile --private-etc=foo --private-tmp --net=none --shell=none --private-dev --private=.  $exe -o -f "$F" &
child=$! 
wait "$child"
